### ISSUE TITLE
[CCE] pvc

### ISSUE THREAD

**Issue by dmicheneau** [FrangipaneTeam/provider-flexibleengine#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The creation of PVC (CCE) resource does not work.
Crossplane creates the PVC resource with an external name, but not on the Flexible Engine web interface.
If I exercise the terraform generated by crossplane, the PVC resource is well created.
We believe that the problem is in importation when crossplane asks the API, on the line: https://github.com/huaweicloud/terraform-huaweicloud/blob/master/huaweicloud/services/cce/resource_huaweicloud_cce_pvc. Go#L348-L349

### Steps To Reproduce

create a crossplane pvc resource with manifest below:

```
apiVersion: cce.flexibleengine.upbound.io/v1beta1
kind: Pvc
metadata:
  annotations:
    meta.upbound.io/example-id: cce/v1beta1/pvc
  labels:
    testing.upbound.io/example-name: example_pvc
  name: example-pvc
spec:
  forProvider:
    accessModes:
    - ReadWriteOnce
    annotations:
      everest.io/disk-volume-type: SSD
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example_cce_cluster
    name: example-pvc
    namespaceSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    storage: 10Gi
    storageClassName: csi-disk
```

locate directory wordir tmp
delete terraform tfstate 
and make a terraform apply.
Magic ! the pvc is created.

### Environment

* Provider Version: 1.35.1
* terrafom: 1.3.7
